//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Role
    {
        public SYS_Role()
        {
            this.SYS_Right = new HashSet<SYS_Right>();
            this.SYS_User = new HashSet<SYS_User>();
        }
    
        public int RoleId { get; set; }
        public string AppId { get; set; }
        public string RoleSign { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<SYS_Right> SYS_Right { get; set; }
        public virtual WX_App WX_App { get; set; }
        public virtual ICollection<SYS_User> SYS_User { get; set; }
    }
}
