//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Right
    {
        public int RightID { get; set; }
        public int RoleId { get; set; }
        public int FunctionID { get; set; }
    
        public virtual SYS_Function SYS_Function { get; set; }
        public virtual SYS_Role SYS_Role { get; set; }
    }
}
