//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Department
    {
        public SYS_Department()
        {
            this.SYS_Department1 = new HashSet<SYS_Department>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string AppId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<SYS_Department> SYS_Department1 { get; set; }
        public virtual SYS_Department SYS_Department2 { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        public virtual WX_App WX_App { get; set; }
    }
}
