//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Function
    {
        public SYS_Function()
        {
            this.SYS_Function1 = new HashSet<SYS_Function>();
            this.SYS_Right = new HashSet<SYS_Right>();
        }
    
        public int FunctionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string FunctionName { get; set; }
        public string FunctionUrl { get; set; }
        public string FunctionType { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SYS_Function> SYS_Function1 { get; set; }
        public virtual SYS_Function SYS_Function2 { get; set; }
        public virtual ICollection<SYS_Right> SYS_Right { get; set; }
    }
}
