//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_App
    {
        public WX_App()
        {
            this.SYS_Department = new HashSet<SYS_Department>();
            this.SYS_Role = new HashSet<SYS_Role>();
            this.SYS_Setting = new HashSet<SYS_Setting>();
            this.SYS_User = new HashSet<SYS_User>();
            this.WX_CustomMsg = new HashSet<WX_CustomMsg>();
            this.WX_Media = new HashSet<WX_Media>();
            this.WX_Menu = new HashSet<WX_Menu>();
            this.WX_QR = new HashSet<WX_QR>();
            this.WX_Queue = new HashSet<WX_Queue>();
            this.WX_User = new HashSet<WX_User>();
            this.WX_UserGroup = new HashSet<WX_UserGroup>();
            this.WX_UserTag = new HashSet<WX_UserTag>();
        }
    
        public string AppId { get; set; }
        public string AppName { get; set; }
        public string AppSecret { get; set; }
        public string WXId { get; set; }
        public string AppType { get; set; }
        public string AppState { get; set; }
        public string CompanyName { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SYS_Department> SYS_Department { get; set; }
        public virtual ICollection<SYS_Role> SYS_Role { get; set; }
        public virtual ICollection<SYS_Setting> SYS_Setting { get; set; }
        public virtual ICollection<SYS_User> SYS_User { get; set; }
        public virtual ICollection<WX_CustomMsg> WX_CustomMsg { get; set; }
        public virtual ICollection<WX_Media> WX_Media { get; set; }
        public virtual ICollection<WX_Menu> WX_Menu { get; set; }
        public virtual ICollection<WX_QR> WX_QR { get; set; }
        public virtual ICollection<WX_Queue> WX_Queue { get; set; }
        public virtual ICollection<WX_User> WX_User { get; set; }
        public virtual ICollection<WX_UserGroup> WX_UserGroup { get; set; }
        public virtual ICollection<WX_UserTag> WX_UserTag { get; set; }
    }
}
