//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_Message
    {
        public string Msg_Id { get; set; }
        public string XmlContent { get; set; }
        public string ToUserName { get; set; }
        public string FromUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Event { get; set; }
        public string Content { get; set; }
        public string MediaId { get; set; }
        public string MsgType { get; set; }
    }
}
