//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WXDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_QR
    {
        public int QRId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AppId { get; set; }
        public string QRName { get; set; }
        public string QR_Scene { get; set; }
        public string QR_Scene_String { get; set; }
        public string QRType { get; set; }
        public Nullable<int> Expire_Seconds { get; set; }
        public string Ticket { get; set; }
        public string QR_URL { get; set; }
        public string Image_URL { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual SYS_User SYS_User { get; set; }
        public virtual WX_App WX_App { get; set; }
    }
}
